language: java

stages:
  - install
  - test
  - coverage

jobs:
  include:
    - stage: install
      script: mvn compile -DskipTests=true -B -V

    - stage: test
      script: mvn test -B

    - stage: coverage
      script: mvn test jacoco:report -B
    - script: mvn coveralls:report -B
