language: java

stages:
  - install
  - test

jobs:
  include:
    - stage: install
      script: mvn compile -DskipTests=true -B

    - stage: test
      script: mvn test -B jacoco:report coveralls:report
